VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IOrder"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("CommandPattern.Command.Abstract")
'@Interface
'@Description : This is the Abstract class which make sure that
'                        Invoker(Broker need not to know how to execute that
'                        buy or sell but it's company concern)

Option Explicit

Public Sub Execute()
    
End Sub

